name: pr
on:  
  pull_request_target:
      types: [assigned, opened, synchronize, reopened]
      branches: [main]

env:
  GO_VERSION: "1.20"

jobs:
  build-and-test:
    uses: ./.github/workflows/base.yaml